# Define parameters of survival analysis
DATASET: TCGA
DATA_INFO: "/home/sg2162/rds/hpc-work/Experiments/clinical/TCGA_included_subjects.json"
OMICS_DIR: "/home/sg2162/rds/rds-pion-p3-3b78hrFsASU/PanCancer/Experiments"
SAVE_OUTCOME_dir: "/home/sg2162/rds/hpc-work/Experiments/TCGA_Pan-Cancer_outcomes"
SAVE_MODEL_DIR: "/home/sg2162/rds/hpc-work/Experiments/outcomes"
OUTCOME:
  VALUE: "MolecularSubtype"
  CHOICES: ["ImmuneSubtype", "MolecularSubtype", "PrimaryDisease"]
TASKS:
  PREDICTION: True

# Define parameters of radiomics
RADIOMICS:
  TARGET: "tumor"
  SEGMENTATOR:
    VALUE: "BiomedParse"
    CHOICES: ["expert", "nnUNet", "BiomedParse"]
  MODE:
    VALUE: "LVMMed"
    CHOICES:
      ["None", "pyradiomics", "SegVol", "BiomedParse", "BayesBP", "LVMMed"]
    # SUFFIX:
    #   - "_tumor_radiomics.json"
    # SUFFIX:
    #   - "_tumor_graph_aggr_mean.npy"
    SUFFIX:
      - "_tumor_layer0_graph_aggr_mean.npy"
      - "_tumor_layer1_graph_aggr_mean.npy"
      - "_tumor_layer2_graph_aggr_mean.npy"
      - "_tumor_layer3_graph_aggr_mean.npy"
      - "_tumor_layer4_graph_aggr_mean.npy"
  # KEYS: ["shape", "firstorder", "glcm", "gldm", "glrlm", "glszm", "ngtdm"]
  # KEYS: ["n_voxels", "mean", "max", "min", "var", "skewness", "kurtosis", "entropy"]
  AGGREGATION: False
  AGGREGATED_MODE:
    VALUE: "None"
    CHOICES: ["None", "MEAN", "ABMIL", "SPARRA"]
  RESOLUTION: 1
  UNITS: "mm"

# Define parameters of pathomics
PATHOMICS:
  MODE:
    VALUE: "UNI"
    CHOICES: ["None", "CNN", "HIPT", "UNI", "CONCH", "CHIEF", "UNI2"]
    SUFFIX:
      - "_graph_aggr_mean.npy"
  # KEYS: ["TUM", "NORM", "DEB"]
  AGGREGATION: False
  AGGREGATED_MODE:
    VALUE: "None"
    CHOICES: ["None", "MEAN", "ABMIL", "SPARRA"]
  RESOLUTION: 20
  UNITS: "power"

# Define parameters of deep aggregation
SPLIT:
  FOLDS: 5
  TEST_RATIO: 0.2
  VALID_RATIO: 0.1
  TRAIN_RATIO: 0.7
  FILTER_SUBJECTS: True # discard subjects without outcomes

PREDICTION:
  USED_OMICS:
    VALUE: "radiopathomics"
    CHOICES: ["radiomics", "pathomics", "radiopathomics"]
  N_JOBS: 32
  MODEL:
    VALUE: "LR"
    CHOICES: ["RF", "XG", "LR", "SVC"]
  REFIT:
    VALUE: "f1"
    CHOICES: ["accuracy", "f1", "roc_auc"]
  FEATURE_SELECTION:
    VALUE: True
    VAR_THRESHOLD: 0.0001
    NUM_FEATURES: 256
  USE_GRAPH_PROPERTIES: False
