# Define parameters of survival analysis
DATASET: TCGA
DATA_INFO: "/home/sg2162/rds/hpc-work/Experiments/clinical/TCGA_included_subjects.json"
OMICS_DIR: "/home/sg2162/rds/rds-pion-p3-3b78hrFsASU/PanCancer/Experiments"
SAVE_OUTCOME_dir: "/home/sg2162/rds/hpc-work/Experiments/TCGA_Pan-Cancer_outcomes"
SAVE_MODEL_DIR: "/home/sg2162/rds/hpc-work/Experiments/outcomes"
OUTCOME:
  VALUE: "StemScoreRNA"
  CHOICES:
    [
      "ImmuneSignatureScore",
      "HRDscore",
      "ImmuneSignatureScore",
      "StemnessScoreDNA",
      "StemScoreRNA",
      "AGE"
    ]
  POOLING: "mean"
TASKS:
  PREDICTION: True

# Define parameters of radiomics
RADIOMICS:
  TARGET: "tumor"
  SEGMENTATOR:
    VALUE: "BiomedParse"
    CHOICES: ["expert", "nnUNet", "BiomedParse"]
  MODE:
    VALUE: "LVMMed"
    CHOICES:
      ["None", "pyradiomics", "SegVol", "BiomedParse", "BayesBP", "LVMMed"]
  AGGREGATION: False
  AGGREGATED_MODE:
    VALUE: "SPARRA"
    CHOICES: ["None", "MEAN", "ABMIL", "SPARRA"]
  RESOLUTION: 1
  UNITS: "mm"

# Define parameters of pathomics
PATHOMICS:
  MODE:
    VALUE: "UNI"
    CHOICES: ["None", "CNN", "HIPT", "UNI", "CONCH", "CHIEF", "UNI2"]
  AGGREGATION: False
  AGGREGATED_MODE:
    VALUE: "SPARRA"
    CHOICES: ["None", "MEAN", "ABMIL", "SPARRA"]
  RESOLUTION: 20
  UNITS: "power"

# Define parameters of deep aggregation
SPLIT:
  FOLDS: 5
  TEST_RATIO: 0.2
  VALID_RATIO: 0.1
  TRAIN_RATIO: 0.7
  FILTER_SUBJECTS: False # discard subjects without outcomes

PREDICTION:
  OMICS_DIR: "/home/sg2162/rds/hpc-work/Experiments/outcomes/TCGA_multitask"
  USED_OMICS:
    VALUE: "radiopathomics"
    CHOICES: ["radiomics", "pathomics", "radiopathomics"]
  N_JOBS: 32
  MODEL:
    VALUE: "ElasticNet"
    CHOICES: ["RF", "Ridge", "LASSO", "ElasticNet", "SVR"]
  REFIT:
    VALUE: "r2"
    CHOICES: ["r2", "neg_mse"]
  OUTCOME_LOGRANK_TEST:
    VALUE: "PFI" # which used to evaluate the risk stratification ability of predicted signature
    CHOICES: ["OS", "DSS", "DFI", "PFI"]
  TARGET_SELECTION:
    VALUE: False
    CROSS_VALID: 5
    PVALUE_THRESHOLD: 0.005
  FEATURE_SELECTION:
    VALUE: False
    VAR_THRESHOLD: 0.0001
    NUM_FEATURES: 256
  USE_GRAPH_PROPERTIES: False
