# Define parameters of pathomics
DATASET: CPTAC
PATHOLOGY: "/home/sg2162/rds/hpc-work/Experiments/clinical/CPTAC_included_subjects.json"
SAVE_DIR: "/home/sg2162/rds/rds-pion-p3-3b78hrFsASU/PanCancer/Experiments/pathomics"
N_JOBS: 32

# Define parameters of pathomics
PATHOMICS:
  MASKING_METHOD:
    VALUE: "otsu"
    CHOICES: ["otsu", "morphological"]
  MODE:
    VALUE: "CHIEF"
    CHOICES: ["CNN", "HIPT", "UNI", "CONCH", "CHIEF", "UNI2"]
  TASKS:
    TISSUE_MASKING: False
    EXTRACTION: False
    GRAPH_CONSTRUCTION: 
      VALUE: False
      SAVE_CLUSTER_POINTS: False # only true for visualization purpose, default false to reduce json file size
    GRAPH_AGGREGATION:
      VALUE: True
      MODE: "mean"
    CONVERT_JSON2NPZ: True
    MEASURE_GRAPH_PROPERTIES: False
    VISUALIZE_PATHOMICS: False
    VISUALIZE_GRAPH: False
  RESOLUTION: 20
  UNITS: "power"
  SKIP_EXITS: True
  DELETE_NPY: True # if true, delete npy after graph construction
  DELETE_JSON: True # if true, delete json after convert json to npz
