# Define parameters of radiomics
DATASET: TCGA
RADIOLOGY: "/home/sg2162/rds/hpc-work/Experiments/clinical/TCGA_included_subjects.json"
DATA_FORMAT: "nifti"
LABEL_DIR: "/home/sg2162/rds/rds-pion-p3-3b78hrFsASU/PanCancer/TCGA_Seg"
SAVE_DIR: "/home/sg2162/rds/rds-pion-p3-3b78hrFsASU/PanCancer/Experiments/radiomics"
N_JOBS: 1

# Define parameters of radiomics
RADIOMICS:
  TARGET: "tumor"
  SEGMENTATOR:
    VALUE: "BiomedParse"
    CHOICES: ["expert", "nnUNet", "BiomedParse"]
  MODE:
    VALUE: "LVMMed"
    CHOICES: ["pyradiomics", "SegVol", "BiomedParse", "BayesBP", "LVMMed"]
    # SUFFIX:
    #   - "radiomics.npy"
    SUFFIX:
      - "layer0_radiomics.npy"
      - "layer1_radiomics.npy"
      - "layer2_radiomics.npy"
      - "layer3_radiomics.npy"
      - "layer4_radiomics.npy"
    FEATURE_DIS_WEIGHT: 0.001 # 0.01 for LVMMed else 0.1
  LAYER_METHOD:
    VALUE: null
    CHOICES: [null, "shells", "peeling"]
  TASKS:
    EXTRACTION: False
    CLUSTERING: False
    GRAPH_CONSTRUCTION: True
    MEASURE_GRAPH_PROPERTIES: False
    VISUALIZE_RADIOMICS: False
    VISUALIZE_GRAPH: False
  BATCH_SIZE: 256
  DILATION_MM: 10
  RESOLUTION: 1
  UNITS: "mm"
  SKIP_EXITS: False
  DELETE_NPY: False # if true, only constructed graphs will be saved
