# Define parameters of radiomics
DATASET: TCGA
RADIOLOGY: "/home/sg2162/rds/hpc-work/Experiments/clinical/TCGA_included_subjects.json"
DATA_FORMAT: "nifti"
LABEL_DIR: "/home/sg2162/rds/rds-pion-p3-3b78hrFsASU/PanCancer/TCGA_Seg"
SAVE_DIR: "/home/sg2162/rds/rds-pion-p3-3b78hrFsASU/PanCancer/Experiments/radiomics"
N_JOBS: 32

# Define parameters of radiomics
RADIOMICS:
  TARGET: "slice" # "tumor", "organ" or "slice"
  SEGMENTATOR:
    VALUE: "BiomedParse"
    CHOICES: ["expert", "nnUNet", "BiomedParse"]
    OBJECT: "tumor" # or "tumor" or "organ"
  MODE:
    VALUE: "LVMMed"
    CHOICES:
      ["pyradiomics", "SegVol", "BiomedParse", "BayesBP", "LVMMed", "FMCIB"]
    SUFFIX:
      - "radiomics.npy"
    # SUFFIX:
    #   - "layer0_radiomics.npy"
    #   - "layer1_radiomics.npy"
    #   - "layer2_radiomics.npy"
    #   - "layer3_radiomics.npy"
    #   - "layer4_radiomics.npy"
  LAYER_METHOD:
    VALUE: null
    CHOICES: [null, "shells", "peeling"]
  TASKS:
    EXTRACTION: True
    CLUSTERING: False
    GRAPH_CONSTRUCTION:
      VALUE: False
      FEATURE_DIS_WEIGHT: 0.1 # 0.01 for LVMMed else 0.1 due to different feature scales, used for clustering in graph construction
      SAVE_CLUSTER_POINTS: False # only true for visualization purpose, default false to reduce json file size
    GRAPH_AGGREGATION:
      VALUE: False
      MODE: "mean"
    CONVERT_JSON2NPZ: False
    MEASURE_GRAPH_PROPERTIES: False
    VISUALIZE_RADIOMICS: False
    VISUALIZE_GRAPH: False
  BATCH_SIZE: 256
  DILATION_MM: 0 # 10 for tumor else 0
  SAMPLING_RATE: 0.01 # set 0.01 to avoid large size npy for whole slice radiomics, 1 for tumor radiomics
  RESOLUTION: 1
  UNITS: "mm"
  SKIP_EXITS: False
  DELETE_NPY: True # if true, delete npy after graph construction
  DELETE_JSON: True # if true, delete json after convert json to npz
