# Define parameters of radiomics
DATASET: CPTAC
RADIOLOGY: "/home/sg2162/rds/hpc-work/Experiments/clinical/CPTAC_included_subjects.json"
DATA_FORMAT: "nifti"
LABEL_DIR: "/home/sg2162/rds/rds-pion-p3-3b78hrFsASU/PanCancer/CPTAC_Seg"
SAVE_DIR: "/home/sg2162/rds/rds-pion-p3-3b78hrFsASU/PanCancer/Experiments/radiomics"
N_JOBS: 32

# Define parameters of radiomics
RADIOMICS:
  TARGET: "tumor"
  SEGMENTATOR:
    VALUE: "BiomedParse"
    CHOICES: ["expert", "nnUNet", "BiomedParse"]
  MODE:
    VALUE: "LVMMed"
    CHOICES: ["pyradiomics", "SegVol", "BiomedParse", "BayesBP", "LVMMed"]
    SUFFIX:
      - "radiomics.npy"
    # SUFFIX:
    #   - "layer0_radiomics.npy"
    #   - "layer1_radiomics.npy"
    #   - "layer2_radiomics.npy"
    #   - "layer3_radiomics.npy"
    #   - "layer4_radiomics.npy"
  LAYER_METHOD:
    VALUE: null
    CHOICES: [null, "shells", "peeling"]
  TASKS:
    EXTRACTION: True
    CLUSTERING: False
    GRAPH_CONSTRUCTION:
      VALUE: False
      FEATURE_DIS_WEIGHT: 0.01 # 0.01 for LVMMed else 0.1, for clustering in graph construction
    GRAPH_AGGREGATION:
      VALUE: False
      MODE: "mean"
    CONVERT_JSON2NPZ: False
    MEASURE_GRAPH_PROPERTIES: False
    VISUALIZE_RADIOMICS: False
    VISUALIZE_GRAPH: False
  BATCH_SIZE: 256
  DILATION_MM: 10
  RESOLUTION: 1
  UNITS: "mm"
  SKIP_EXITS: False
  DELETE_NPY: False # if true, only constructed graphs will be saved
